### PR TITLE
update dcp_pops and hra_data to latest and update issue template

### PR DESCRIPTION
**Pull request by mbh329**
Default to latest version of dcp_pops, both sql and python scripts worked

### CODE REVIEW

**Comment by mbh329** [comment]
Used this branch to also update the hra data in the datasets.yml, remove the deprecated hra_centers as it is no longer used for facdb, and update hra_jobcenters, hra_medicaid, hra_snapcenters in issue template

**Review by SashaWeinstein — CHANGES_REQUESTED** [review]
I will try running this code on my machine but before I do the version of dcp_facilities should go back to default, the PR I opened addresses this

**Review by SashaWeinstein — COMMENTED** [review]
The new datasets work on my machine. Once the version in dataloading is corrected I think this will be good to merge

**Comment by mbh329** [comment]
removed the version by date in dcp_facilities to go back to default

**Review by SashaWeinstein — APPROVED** [review]
Change to dataloading looks good

**Pull request merged**
