### PR TITLE
Finish merging feature branch 553

### PR DESCRIPTION
**Pull request by SashaWeinstein**
When I opened PR #550 I forgot to push two commits from my local machine which have changes that are necessary to get the associated page on the QAQC app to work.

The key thing here is to replace `wogeom_old/new` with `with_geom_old/new` so the logic on the QAQC side can work in the affirmative which I find much easier

### CODE REVIEW

**Review by mbh329 — APPROVED** [review]
Ran on my local machine and looks good

**Comment by mbh329** [comment]
Do the columns also need to be changed in the `app.py` file?

**Comment by SashaWeinstein** [comment]
Sorry, I don't know what app.py file you're talking about

**Comment by mbh329** [comment]
I searched the repo for the old column names and in `dashboard/app.py` script they still exist. the dashboard is deprecated and all qa/qc is handled by that specific qaqc repo no?

**Comment by SashaWeinstein** [comment]
Yes, that's correct. We should probably take out the dashboard folder

**Comment by mbh329** [comment]
That makes sense to me, just to avoid any confusion

**Pull request merged**
